#!/usr/bin/env python3
"""Generate the ChaCha20-Poly1305 KAT header for the bare-metal demo.

The RFC 8439 Sec 2.8.2 AEAD vector is taken verbatim from the copy already in
this repo (generators/sha3/software/tests/src/chachapoly_wolfssl_official.c).
The ChaCha20-only and Poly1305-only sub-vectors are then produced by the
reference implementations below, which are checked against that AEAD vector
first -- so if the check passes, the intermediates are consistent with a known
good end-to-end result rather than transcribed by hand.
"""
import struct, sys

MASK = 0xFFFFFFFF

def rotl(v, n):
    return ((v << n) | (v >> (32 - n))) & MASK

def qr(x, a, b, c, d):
    x[a] = (x[a] + x[b]) & MASK; x[d] = rotl(x[d] ^ x[a], 16)
    x[c] = (x[c] + x[d]) & MASK; x[b] = rotl(x[b] ^ x[c], 12)
    x[a] = (x[a] + x[b]) & MASK; x[d] = rotl(x[d] ^ x[a], 8)
    x[c] = (x[c] + x[d]) & MASK; x[b] = rotl(x[b] ^ x[c], 7)

def chacha20_block(key, counter, nonce):
    st = [0x61707865, 0x3320646e, 0x79622d32, 0x6b206574]
    st += list(struct.unpack("<8I", key))
    st += [counter]
    st += list(struct.unpack("<3I", nonce))
    w = list(st)
    for _ in range(10):
        qr(w, 0, 4, 8, 12); qr(w, 1, 5, 9, 13); qr(w, 2, 6, 10, 14); qr(w, 3, 7, 11, 15)
        qr(w, 0, 5, 10, 15); qr(w, 1, 6, 11, 12); qr(w, 2, 7, 8, 13); qr(w, 3, 4, 9, 14)
    return struct.pack("<16I", *[(w[i] + st[i]) & MASK for i in range(16)])

def chacha20_xor(key, counter, nonce, data):
    out = bytearray()
    for i in range(0, len(data), 64):
        ks = chacha20_block(key, counter + i // 64, nonce)
        blk = data[i:i + 64]
        out += bytes(a ^ b for a, b in zip(blk, ks))
    return bytes(out)

P130_5 = (1 << 130) - 5

def poly1305(key, msg):
    r = int.from_bytes(key[:16], "little") & 0x0ffffffc0ffffffc0ffffffc0fffffff
    s = int.from_bytes(key[16:], "little")
    acc = 0
    for i in range(0, len(msg), 16):
        blk = msg[i:i + 16]
        n = int.from_bytes(blk + b"\x01", "little")
        acc = ((acc + n) * r) % P130_5
    return ((acc + s) & ((1 << 128) - 1)).to_bytes(16, "little")

def pad16(b):
    return b"\x00" * ((16 - len(b) % 16) % 16)

def aead_encrypt(key, nonce, aad, pt):
    otk = chacha20_block(key, 0, nonce)[:32]
    ct = chacha20_xor(key, 1, nonce, pt)
    mac_data = aad + pad16(aad) + ct + pad16(ct)
    mac_data += struct.pack("<Q", len(aad)) + struct.pack("<Q", len(ct))
    return ct, poly1305(otk, mac_data), otk, mac_data

# --- RFC 8439 Sec 2.8.2, copied from chachapoly_wolfssl_official.c -----------
KEY   = bytes(range(0x80, 0xa0))
NONCE = bytes([0x07, 0x00, 0x00, 0x00, 0x40, 0x41, 0x42, 0x43, 0x44, 0x45, 0x46, 0x47])
AAD   = bytes([0x50, 0x51, 0x52, 0x53, 0xc0, 0xc1, 0xc2, 0xc3, 0xc4, 0xc5, 0xc6, 0xc7])
PT    = (b"Ladies and Gentlemen of the class of '99: If I could offer you only "
         b"one tip for the future, sunscreen would be it.")
CT_EXPECT = bytes.fromhex(
    "d31a8d34648e60db7b86afbc53ef7ec2a4aded51296e08fea9e2b5a736ee62d6"
    "3dbea45e8ca9671282fafb69da92728b1a71de0a9e060b2905d6a5b67ecd3b36"
    "92ddbd7f2d778b8c9803aee328091b58fab324e4fad675945585808b4831d7bc"
    "3ff4def08e4b7a9de576d26586cec64b6116")
TAG_EXPECT = bytes.fromhex("1ae10b594f09e26a7e902ecbd0600691")

ct, tag, otk, _ = aead_encrypt(KEY, NONCE, AAD, PT)
if ct != CT_EXPECT or tag != TAG_EXPECT:
    sys.exit("reference implementation disagrees with the RFC 8439 Sec 2.8.2 vector")
print("reference validated against RFC 8439 Sec 2.8.2")

# --- RFC 8439 Sec 2.4.2: ChaCha20 encryption, counter starts at 1 -----------
C_KEY   = bytes(range(0x00, 0x20))
C_NONCE = bytes([0, 0, 0, 0, 0, 0, 0, 0x4a, 0, 0, 0, 0])
C_PT    = PT
C_CT    = chacha20_xor(C_KEY, 1, C_NONCE, C_PT)

# --- RFC 8439 Sec 2.5.2: Poly1305 ------------------------------------------
P_KEY = bytes.fromhex("85d6be7857556d337f4452fe42d506a8"
                      "0103808afb0db2fd4abff6af4149f51b")
P_MSG = b"Cryptographic Forum Research Group"
P_TAG = poly1305(P_KEY, P_MSG)
assert P_TAG == bytes.fromhex("a8061dc1305136c6c22b8baf0c0127a9"), P_TAG.hex()
print("poly1305 reference matches RFC 8439 Sec 2.5.2")

def carr(name, b):
    body = ", ".join("0x%02X" % x for x in b)
    return "static const uint8_t %s[%d] = {%s};" % (name, len(b), body)

L = []
w = L.append
w("/* Generated by fpga/sw/chachapoly_aead/gen_kats.py -- do not edit by hand.")
w(" *")
w(" * RFC 8439 vectors:")
w(" *   Sec 2.4.2  ChaCha20 encryption")
w(" *   Sec 2.5.2  Poly1305 tag")
w(" *   Sec 2.8.2  Poly1305 one-time key (ChaCha20 block 0 of the AEAD run)")
w(" *   Sec 2.8.2  ChaCha20-Poly1305 AEAD")
w(" *")
w(" * The Sec 2.8.2 vector is the copy already carried in this repo at")
w(" * generators/sha3/software/tests/src/chachapoly_wolfssl_official.c. The")
w(" * generator reproduces it with its own reference implementation before")
w(" * emitting anything, so the other vectors are consistent with a known good")
w(" * end-to-end result.")
w(" */")
w("")
w("#ifndef CHACHAPOLY_KATS_H")
w("#define CHACHAPOLY_KATS_H")
w("")
w("#include <stdint.h>")
w("")
w("/* ---- RFC 8439 Sec 2.4.2: ChaCha20, block counter starts at 1 --------- */")
w("#define KAT_CHACHA_COUNTER 1")
w(carr("kat_chacha_key", C_KEY))
w(carr("kat_chacha_nonce", C_NONCE))
w(carr("kat_chacha_pt", C_PT))
w(carr("kat_chacha_ct", C_CT))
w("")
w("/* ---- RFC 8439 Sec 2.5.2: Poly1305 ----------------------------------- */")
w(carr("kat_poly_key", P_KEY))
w(carr("kat_poly_msg", P_MSG))
w(carr("kat_poly_tag", P_TAG))
w("")
w("/* ---- Poly1305 one-time key: ChaCha20 block 0 bytes 0..31, per Sec 2.8.2 */")
w(carr("kat_otk_key", KEY))
w(carr("kat_otk_nonce", NONCE))
w(carr("kat_otk_expect", otk))
w("")
w("/* ---- RFC 8439 Sec 2.8.2: AEAD --------------------------------------- */")
w(carr("kat_aead_key", KEY))
w(carr("kat_aead_nonce", NONCE))
w(carr("kat_aead_aad", AAD))
w(carr("kat_aead_pt", PT))
w(carr("kat_aead_ct", CT_EXPECT))
w(carr("kat_aead_tag", TAG_EXPECT))
w("")
w("#endif /* CHACHAPOLY_KATS_H */")

open("fpga/sw/chachapoly_aead/src/chachapoly_kats.h", "w").write("\n".join(L) + "\n")
print("written: pt=%d ct=%d" % (len(PT), len(CT_EXPECT)))
