#!/usr/bin/env python3
"""Generate the ASCON KAT header for the standard (SP 800-232) accelerator.

Run from the repo root:

    python3 fpga/sw/ascon/gen_kats.py

Vectors are a subset of the upstream ascon-c KAT files vendored under
fpga/sw/edhoc/uoscore-uedhoc/externals/ascon-c. All four SP 800-232 algorithms
are covered, including the empty-input cases: the engine handles a zero-length
message, AD and plaintext natively.
"""

import sys

A = "fpga/sw/edhoc/uoscore-uedhoc/externals/ascon-c"

# The wrapper's output capture buffer is 16 x 64-bit, so a single XOF/CXOF
# request tops out at 128 bytes. 32 bytes is used here: it matches Hash256 and
# exercises multiple squeeze iterations without approaching the cap.
XOF_OUT = 32


def parse(path):
    """Records are runs of 'Key = VALUE' lines separated by blank lines."""
    recs, cur = [], {}
    for line in open(path):
        line = line.strip()
        if not line:
            if cur:
                recs.append(cur)
                cur = {}
            continue
        k, _, v = line.partition("=")
        cur[k.strip()] = v.strip()
    if cur:
        recs.append(cur)
    return recs


hash_k = parse(f"{A}/crypto_hash/asconhash256/LWC_HASH_KAT_128_256.txt")
xof_k = parse(f"{A}/crypto_hash/asconxof128/LWC_XOF_KAT_128_512.txt")
cxof_k = parse(f"{A}/crypto_cxof/asconcxof128/LWC_CXOF_KAT_128_512.txt")
aead_k = parse(f"{A}/crypto_aead/asconaead128/LWC_AEAD_KAT_128_128.txt")

if not (hash_k and xof_k and cxof_k and aead_k):
    sys.exit("could not parse the vendored ascon-c KAT files")


def pick_by_len(recs, key, wanted):
    """First record for each requested length of field `key`."""
    out, seen = [], set()
    for r in recs:
        n = len(r[key]) // 2
        if n in wanted and n not in seen:
            seen.add(n)
            out.append(r)
    return out


def pick_by_pair(recs, k1, k2, wanted):
    out, seen = [], set()
    for r in recs:
        k = (len(r[k1]) // 2, len(r[k2]) // 2)
        if k in wanted and k not in seen:
            seen.add(k)
            out.append(r)
    return out


# Lengths straddle the 8-byte rate boundary in both directions; 0 is included
# because the standard defines it.
hs = pick_by_len(hash_k, "Msg", {0, 1, 7, 8, 9, 15, 16, 17, 32})
xs = pick_by_len(xof_k, "Msg", {0, 1, 7, 8, 9, 16})
cs = pick_by_pair(cxof_k, "Msg", "Z", {(0, 0), (0, 4), (1, 1), (1, 8), (3, 3), (8, 16), (16, 8)})
az = pick_by_pair(aead_k, "PT", "AD",
                  {(0, 0), (0, 1), (1, 0), (1, 1), (8, 3), (16, 16), (17, 8), (32, 17)})


def carr(name, hexstr):
    b = bytes.fromhex(hexstr)
    if not b:
        return f"static const uint8_t {name}[1] = {{0}};"
    body = ", ".join("0x%02X" % x for x in b)
    return f"static const uint8_t {name}[{len(b)}] = {{{body}}};"


L = []
w = L.append
w("/* Generated by fpga/sw/ascon/gen_kats.py -- do not edit by hand.")
w(" *")
w(" * Subset of the upstream ascon-c KAT files vendored at")
w(" * fpga/sw/edhoc/uoscore-uedhoc/externals/ascon-c:")
w(" *   crypto_hash/asconhash256/LWC_HASH_KAT_128_256.txt")
w(" *   crypto_hash/asconxof128/LWC_XOF_KAT_128_512.txt")
w(" *   crypto_cxof/asconcxof128/LWC_CXOF_KAT_128_512.txt")
w(" *   crypto_aead/asconaead128/LWC_AEAD_KAT_128_128.txt")
w(" *")
w(" * All four NIST SP 800-232 algorithms, including the empty-input cases.")
w(" *")
w(f" * XOF and CXOF digests are truncated to {XOF_OUT} bytes.")
w(" */")
w("")
w("#ifndef ASCON_KATS_H")
w("#define ASCON_KATS_H")
w("")
w("#include <stdint.h>")
w("")

w("/* ---- Ascon-Hash256, 32-byte digest ---------------------------------- */")
for i, r in enumerate(hs):
    w(carr(f"kat_hash_msg_{i}", r["Msg"]))
    w(carr(f"kat_hash_md_{i}", r["MD"]))
w("")
w("struct ascon_hash_kat { const uint8_t *msg; uint32_t msg_len; const uint8_t *md; };")
w("static const struct ascon_hash_kat ascon_hash_kats[] = {")
for i, r in enumerate(hs):
    w(f"\t{{ kat_hash_msg_{i}, {len(r['Msg'])//2}, kat_hash_md_{i} }},")
w("};")
w("")

w(f"/* ---- Ascon-XOF128, first {XOF_OUT} bytes ------------------------------------ */")
w(f"#define ASCON_XOF_KAT_LEN {XOF_OUT}")
for i, r in enumerate(xs):
    w(carr(f"kat_xof_msg_{i}", r["Msg"]))
    w(carr(f"kat_xof_md_{i}", r["MD"][:XOF_OUT * 2]))
w("")
w("struct ascon_xof_kat { const uint8_t *msg; uint32_t msg_len; const uint8_t *md; };")
w("static const struct ascon_xof_kat ascon_xof_kats[] = {")
for i, r in enumerate(xs):
    w(f"\t{{ kat_xof_msg_{i}, {len(r['Msg'])//2}, kat_xof_md_{i} }},")
w("};")
w("")

w(f"/* ---- Ascon-CXOF128, first {XOF_OUT} bytes; Z is the customization string --- */")
w(f"#define ASCON_CXOF_KAT_LEN {XOF_OUT}")
for i, r in enumerate(cs):
    w(carr(f"kat_cxof_z_{i}", r["Z"]))
    w(carr(f"kat_cxof_msg_{i}", r["Msg"]))
    w(carr(f"kat_cxof_md_{i}", r["MD"][:XOF_OUT * 2]))
w("")
w("struct ascon_cxof_kat { const uint8_t *z; uint32_t z_len;")
w("                        const uint8_t *msg; uint32_t msg_len; const uint8_t *md; };")
w("static const struct ascon_cxof_kat ascon_cxof_kats[] = {")
for i, r in enumerate(cs):
    w(f"\t{{ kat_cxof_z_{i}, {len(r['Z'])//2}, kat_cxof_msg_{i}, {len(r['Msg'])//2}, kat_cxof_md_{i} }},")
w("};")
w("")

w("/* ---- Ascon-AEAD128: ct holds ciphertext followed by the 16-byte tag --- */")
for i, r in enumerate(az):
    w(carr(f"kat_aead_key_{i}", r["Key"]))
    w(carr(f"kat_aead_npub_{i}", r["Nonce"]))
    w(carr(f"kat_aead_ad_{i}", r["AD"]))
    w(carr(f"kat_aead_pt_{i}", r["PT"]))
    w(carr(f"kat_aead_ct_{i}", r["CT"]))
w("")
w("struct ascon_aead_kat { const uint8_t *key; const uint8_t *npub;")
w("                        const uint8_t *ad; uint32_t ad_len;")
w("                        const uint8_t *pt; uint32_t pt_len;")
w("                        const uint8_t *ct; };")
w("static const struct ascon_aead_kat ascon_aead_kats[] = {")
for i, r in enumerate(az):
    w(f"\t{{ kat_aead_key_{i}, kat_aead_npub_{i}, kat_aead_ad_{i}, {len(r['AD'])//2},")
    w(f"\t  kat_aead_pt_{i}, {len(r['PT'])//2}, kat_aead_ct_{i} }},")
w("};")
w("")
w("#endif /* ASCON_KATS_H */")

open("fpga/sw/ascon/src/ascon_kats.h", "w").write("\n".join(L) + "\n")
print("hash=%d xof=%d cxof=%d aead=%d  (total %d vectors)"
      % (len(hs), len(xs), len(cs), len(az), len(hs) + len(xs) + len(cs) + len(az)))
